project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  reader-mode: true
  repo-url: https://github.com/zule-lab/quarto-resources
  repo-actions: [edit, issue]
  navbar:
    title: 'ZULE Lab Resources & Policies'
    right:
      - icon: github
        href: https://github.com/zule-lab/quarto-resources
  sidebar:
    contents:
      - index.qmd
      - policies.qmd
      - spatial-resources.qmd
      - other-resources.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
