---
title: "Introduction"
author: "Isabella C. Richmond + Alec L. Robitaille"
date: "`r Sys.Date()`"
listing:
  - contents: "*/**qmd"
    type: table
    fields: [title, file-modified]
    date-format: iso
    max-items: 5
    sort: "file-modified desc"
---

Template literature base using `quarto`.

It is structured as a website since quarto books require the chapters
to be explicitly listed in the `_quarto.yml` which doesn't gel super 
well with this type of quickly growing literature base. Each file
represents a paper, or a topic, or a book, and listing each as a chapter
is too cumbersome. 

Listing pages are used to show all the pages within the subdirectories,
easily searched or sorted. 


## Usage

1. Fork/copy/get repo
1. Remove example tree documents
1. Replace with your own documents 
1. Adjust listing pages relevant to your subdirectory structure
1. Adjust `_quarto.yml`


## Resources

- [Quarto websites](https://quarto.org/docs/websites/)
	- [Listing pages](https://quarto.org/docs/websites/website-listings.html)
- [Quarto GitHub Actions](https://github.com/quarto-dev/quarto-actions)


## TODO

- List subfolder or path in listing pages?
- Networks


## Recently modified pages

