---
title: "ZULE Lab Reading List"
editor: visual
---

Below is a short list of some papers that will get you started in the ZULE Lab. For a more comprehensive list of papers based on all the topics we cover in the lab, take a look through the lab's shared Zotero library.

| Title                                                                                                                                               | Authors                                                                                                                                             | Year | Journal                      | Link                                                                                                                                                                                                   |
|---------------|---------------|---------------|---------------|---------------|
| The biodiversity-ecosystem service relationship in urban areas: a quantitative review                                                               | Carly Ziter                                                                                                                                         | 2015 | Oikos                        | <https://onlinelibrary-wiley-com.lib-ezproxy.concordia.ca/doi/full/10.1111/oik.02883?casa_token=25Lrxw6w8p0AAAAA%3AyKXztAvEwp8EkwdD3m_ge5iUaOSdvHEzO8t4B2g4-JAiP24LNoN8eklj8hDet9c-QGQs3yIX_9tM1Hfr>   |
| Capacity, pressure, demand, and flow: A conceptual framework for analyzing ecosystem service provision and delivery                                 | Amy Villamagna, Paul Angermeier, Elena Bennett                                                                                                      | 2013 | Ecological Complexity        | <https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S1476945X1300055X?casa_token=9G_NQu7JYugAAAAA:31BkkXR7y_Qr6XW80zhKN4csGGbeVv4K5UPt67yX3JSqQnNmh96AA1PzO9WliJslmUump_rb_gY> |
| Managing urban ecosystems for goods and services                                                                                                    | Kevin J Gaston, Maria L Avila-Jimenez, Jill L Edmondson                                                                                             | 2013 | Journal of Applied Ecology   | <https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.12087>                                                                                                                         |
| Key insights for the future of urban ecosystem services research                                                                                    | Peleg Kremer, Zoe Hamstead, Dagmar Haase, Timon McPhearson, Erik Andersson, et al.                                                                  | 2016 | Ecology and Society          | <https://www-jstor-org/stable/26270402?seq=1#metadata_info_tab_contents>                                                                                                                               |
| Advancing urban ecology toward a science of cities                                                                                                  | Timon McPhearson et al                                                                                                                              | 2016 | BioScience                   | <https://academic-oup-com.lib-ezproxy.concordia.ca/bioscience/article/66/3/198/2470145?login=true>                                                                                                     |
| The ecological and evolutionary consequences of systemic racism in urban environments                                                               | Christopher J Schell, Karen Dyson, Tracy L Fuentes, Simone Des Roches, Nyeema C Harris, Danica Sterud Miller, Cleo A Woelfle-Erskine, Max R Lambert | 2020 | Science                      | <https://science.sciencemag.org/content/369/6510/eaay4497.abstract?casa_token=mUfe5sNSq08AAAAA:usmy2vvxiYrmcTPqK7qMBovHWPlGifDmt5lrFc_WqrxTFUPn-XSdGN5MNSK419476SB8zU4vBVLDxYk>                        |
| Convergence of urban forest and socio-economic indicators of resilience: A study of environmental inequality in four major cities in eastern Canada | Felix Landry, Jerome Dupras, Christian Messier                                                                                                      | 2020 | Landscape and Urban Planning | <https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S0169204619313349?casa_token=KkpkaKCeEfwAAAAA:TCEZYmvXOn9B0D67BPzB0Qo6UiWlKwaeL5_bbuiBhX_ZDJEfKRFj7VTs6J_NUJuNE8niegbuuBw> |
| Biodiversity in cities needs space: a meta-analysis of factors determining intra-urban biodiversity variation                                       | Beninde, Veith, Hochkirch                                                                                                                           | 2015 | Ecology Letters              | <https://onlinelibrary.wiley.com/doi/full/10.1111/ele.12427>                                                                                                                                           |
| The Biological Deserts Fallacy: Cities in Their Landscapes Contribute More than We Think to Regional Biodiversity                                   | Spotswood et al                                                                                                                                     | 2021 | BioScience                   | <https://academic-oup-com.lib-ezproxy.concordia.ca/bioscience/article/71/2/148/6102678>                                                                                                                |
| Global change and the ecology of cities                                                                                                             | Grimm, N. B., S. H. Faeth, N. E. Golubiewski, C. L. Redman, J. Wu, X. Bai, and J. M. Briggs                                                         | 2008 | Science                      | <https://www.science.org/doi/abs/10.1126/science.1150195>                                                                                                                                              |
