---
title: "Soil Reading List"
editor: visual
---

**Urban Soils**

**Here's a starting list of some (mostly recent) urban soils work, including a handful of authors to look out for in particular. Don't feel like you have to read all of these right away. Skim the abstracts and see which ones seem most interesting/useful for you.**

My previous work:

Ziter C, Turner MG. 2018. Current and historical land use influence soil-based ecosystem services in an urban landscape. Ecological Applications 28: 643-654 [\[PDF\]](https://www.carlyziter.com/uploads/5/3/4/6/53462323/ecological_applications_2018_ziter.pdf)

Ziter C, Graves RA, Turner MG. 2017. How do land-use legacies affect ecosystem services in United States cultural landscapes? Landscape Ecology 32: 2205-2218 [\[PDF\]](https://www.carlyziter.com/uploads/5/3/4/6/53462323/landscape_ecol_2017_ziter.pdf)

General Urban Soil Ecology/ES

Book: Diana Wall. Soil Ecology and Ecosystem Services (will put physical copy in the lab)

Book Chapter: M Pavao-Zuckerman, R Pouyat. The effects of urban expansion on soil health and ecosystem services

<https://www.taylorfrancis.com/chapters/edit/10.4324/9781315715674-6/effects-urban-expansion-soil-health-ecosystem-services-mitchell-pavao-zuckerman-richard-pouyat>

Bryn. 2007. Habitat structure: A fundamental concept and framework for urban soil ecology: <https://link.springer.com/article/10.1007/s11252-007-0027-6> 

Setala et al. 2013. Urban and agricultural soils: conflicts and trade-offs in the optimization of ecosystem services: <https://link.springer.com/article/10.1007/s11252-013-0311-6> 

Pouyat et al. 2017. Introducing GLUSEEN: a new open access and experimental network in urban soil ecology: <https://academic.oup.com/jue/article/3/1/jux002/3062424?login=true>

**Some good researchers to look out for:**

Dustin Herrmann's (& Lara Schifman's) work

Widespread loss of intermediate soil horizons in urban landscapes: <https://www.pnas.org/content/115/26/6751.short>

Urbanization drives convergence in soil profile texture and carbon content: <https://iopscience.iop.org/article/10.1088/1748-9326/abbb00/meta>

Vacant urban lot soils and their potential to support ecosystem services: <https://www.jstor.org/stable/44245287?casa_token=2-8Ei_i0HG0AAAAA%3AlMvlS8QYhehwNWKvo4YMW0O5G9SKqZ-a12lg-2WzRrBAW2valcYCDk-KLg0uvE_UlOz0-JCZPlCdknr_JJRH5WJG4YquKEIwVROZw98q1UT3q5IpeXG34g&seq=1#metadata_info_tab_contents> 

Jill Edmondson's work

Land-cover effects on soil organic carbon stocks in a European city: <https://www.sciencedirect.com/science/article/pii/S0048969713013065>

Soil surface temperatures reveal moderation of the urban heat island effect by trees and shrubs <https://www.nature.com/articles/srep33708>

Are soils in urban ecosystems compacted? A citywide analysis: <https://royalsocietypublishing.org/doi/full/10.1098/rsbl.2011.0260>

Urban Tree Effects on Soil Organic Carbon: <https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0101872> 

Richard Pouyat (he did some of the earlier/fundamental work on urban soils)
