---
title: "Cross-City Ecosystem Services Reading List"
editor: visual
---

| **Title**                                                                                                                                           | **Authors**                                                                                                                                         | **Year** | **Journal**                     | **Link**                                                                                                                                                                                                                                                                                                                                                                              |
|-----------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------|----------|---------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Scale and context dependence of ecosystem service providing units                                                                                   | Erik Andersson, Timon McPhearson, Peleg Kremer, Erik Gomez-Baggethun, Dagmar Haase, Magnus Tuvendal, Daniel Wurster                                 | 2014     | Ecosystem Services              | [https://www-sciencedirect-com/science/article/pii/S2212041614000850?casa_token=bjKJrjZbVWcAAAAA:MMPEA9UeOhZJvJrDTqRcYA3BrNo-v3SoTLlINJlxH8fRT_HFSzsK6xrkyIe9d2Q5ThHRf_bjwfw](https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S2212041614000850?casa_token=bjKJrjZbVWcAAAAA:MMPEA9UeOhZJvJrDTqRcYA3BrNo-v3SoTLlINJlxH8fRT_HFSzsK6xrkyIe9d2Q5ThHRf_bjwfw)   |
| The social production of ecosystem services: A framework for studying environmental justice and ecological complexity in urban landscapes           | Henrik Ernstson                                                                                                                                     | 2013     | Landscape and Urban Planning    | [https://www-sciencedirect-com/science/article/pii/S0169204612002861](https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S0169204612002861)                                                                                                                                                                                                                   |
| Managing urban ecosystems for goods and services                                                                                                    | Kevin J Gaston, Maria L Avila-Jimenez, Jill L Edmondson                                                                                             | 2013     | Journal of Applied Ecology      | <https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2664.12087>                                                                                                                                                                                                                                                                                                        |
| Key insights for the future of urban ecosystem services research                                                                                    | Peleg Kremer, Zoe Hamstead, Dagmar Haase, Timon McPhearson, Erik Andersson, et al.                                                                  | 2016     | Ecology and Society             | [https://www-jstor-org/stable/26270402?seq=1#metadata_info_tab_contents](https://www-jstor-org.lib-ezproxy.concordia.ca/stable/26270402?seq=1#metadata_info_tab_contents)                                                                                                                                                                                                             |
| Advancing urban ecology toward a science of cities                                                                                                  | Timon McPhearson et al                                                                                                                              | 2016     | BioScience                      | [https://academic-oup-com/bioscience/article/66/3/198/2470145?login=true](https://academic-oup-com.lib-ezproxy.concordia.ca/bioscience/article/66/3/198/2470145?login=true)                                                                                                                                                                                                           |
| Urban tree diversity - Taking stock and looking ahead                                                                                               | J Morgenroth et al                                                                                                                                  | 2015     | Urban Forestry & Urban Greening | [https://www-sciencedirect-com/science/article/pii/S1618866715001557?casa_token=m0SgPfnxOEUAAAAA:TyDUrmp_hVF3XFvrZl6kxLrrpZ1fZHVav0IScVoDemWOyg-B2QLEKhETALViMaUtHjgYOf7Y3zg](https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S1618866715001557?casa_token=m0SgPfnxOEUAAAAA:TyDUrmp_hVF3XFvrZl6kxLrrpZ1fZHVav0IScVoDemWOyg-B2QLEKhETALViMaUtHjgYOf7Y3zg)   |
| Ecosystems and Human Well-Being Health Synthesis                                                                                                    | Millennium Ecosystem Assessment                                                                                                                     | 2005     | World Health Organization       | <https://apps.who.int/iris/bitstream/handle/10665/43354/9241563095.pdf>                                                                                                                                                                                                                                                                                                               |
| Disentangling the effects of urban form and socio-demographic context on street tree cover: A multi-level analysis from Montréal                    | Thi-Thanh-Hien Pham, Philippe Apparicio, Shawn Landry, Joseph Lewnard                                                                               | 2017     | Landscape and Urban Planning    | [https://www-sciencedirect-com/science/article/pii/S0169204616301797?casa_token=CMwETA5UjYkAAAAA:WNyZiw0HriP4qSrvQhFDjycX7UGf8RsTUFM7iD8xmNDgxPYIGctrZ\-\--g-KcY5lM5mHC7We_M50](https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S0169204616301797?casa_token=CMwETA5UjYkAAAAA:WNyZiw0HriP4qSrvQhFDjycX7UGf8RsTUFM7iD8xmNDgxPYIGctrZ---g-KcY5lM5mHC7We_M50) |
| Understanding relationships among ecosystem services across spatial scales and over time                                                            | Jiangxiao Qiu, Stephen R Carpenter, Eric G Booth, Melissa Motew, Samuel C Zipper, Christopher J Kucharik, Steven P Loheide II, Monica G Turner      | 2018     | Environmental Research Letters  | <https://iopscience.iop.org/article/10.1088/1748-9326/aabb87/meta>                                                                                                                                                                                                                                                                                                                    |
| The ecological and evolutionary consequences of systemic racism in urban environments                                                               | Christopher J Schell, Karen Dyson, Tracy L Fuentes, Simone Des Roches, Nyeema C Harris, Danica Sterud Miller, Cleo A Woelfle-Erskine, Max R Lambert | 2020     | Science                         | <https://science.sciencemag.org/content/369/6510/eaay4497.abstract?casa_token=mUfe5sNSq08AAAAA:usmy2vvxiYrmcTPqK7qMBovHWPlGifDmt5lrFc_WqrxTFUPn-XSdGN5MNSK419476SB8zU4vBVLDxYk>                                                                                                                                                                                                       |
| Capacity, pressure, demand, and flow: A conceptual framework for analyzing ecosystem service provision and delivery                                 | Amy Villamagna, Paul Angermeier, Elena Bennett                                                                                                      | 2013     | Ecological complexity           | [https://www-sciencedirect-com/science/article/pii/S1476945X1300055X?casa_token=9G_NQu7JYugAAAAA:31BkkXR7y_Qr6XW80zhKN4csGGbeVv4K5UPt67yX3JSqQnNmh96AA1PzO9WliJslmUump_rb_gY](https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S1476945X1300055X?casa_token=9G_NQu7JYugAAAAA:31BkkXR7y_Qr6XW80zhKN4csGGbeVv4K5UPt67yX3JSqQnNmh96AA1PzO9WliJslmUump_rb_gY)   |
| Convergence of urban forest and socio-economic indicators of resilience: A study of environmental inequality in four major cities in eastern Canada | Felix Landry, Jerome Dupras, Christian Messier                                                                                                      | 2020     | Landscape and Urban Planning    | [https://www-sciencedirect-com/science/article/pii/S0169204619313349?casa_token=KkpkaKCeEfwAAAAA:TCEZYmvXOn9B0D67BPzB0Qo6UiWlKwaeL5_bbuiBhX_ZDJEfKRFj7VTs6J_NUJuNE8niegbuuBw](https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S0169204619313349?casa_token=KkpkaKCeEfwAAAAA:TCEZYmvXOn9B0D67BPzB0Qo6UiWlKwaeL5_bbuiBhX_ZDJEfKRFj7VTs6J_NUJuNE8niegbuuBw)   |
| Data archiving in ecology and evolution: best practices                                                                                             | Michael C Whitlock                                                                                                                                  | 2010     | Trends in Ecology and Evolution | [https://www-sciencedirect-com/science/article/pii/S0169534710002697?casa_token=ELf-b7q4cIcAAAAA:0cOyskla5CVe6k2rmh2afXS8gsMq8-zkUtaHgGEbPwQqh_DAVyT4mqpUmoSeQ7jvOrL5Gs95dXw](https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S0169534710002697?casa_token=ELf-b7q4cIcAAAAA:0cOyskla5CVe6k2rmh2afXS8gsMq8-zkUtaHgGEbPwQqh_DAVyT4mqpUmoSeQ7jvOrL5Gs95dXw)   |
| Assessing the sensitivity of urban ecosystem service maps to input spatial data resolution and method choice                                        | Chang Zhao, Heather A Sander                                                                                                                        | 2018     | Landscape and Urban Planning    | [https://www-sciencedirect-com/science/article/pii/S0169204618300768?casa_token=Bbot97pNlVsAAAAA:0Ceh18wR_LUl3YctdIsFyS1y9jskmg6zcF-S_qCAMrY1cAfaaNFdOe54u2AQWMHaBu9Sg0JNxIw](https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S0169204618300768?casa_token=Bbot97pNlVsAAAAA:0Ceh18wR_LUl3YctdIsFyS1y9jskmg6zcF-S_qCAMrY1cAfaaNFdOe54u2AQWMHaBu9Sg0JNxIw)   |
| The biodiversity-ecosystem service relationship in urban areas: a quantitative review                                                               | Carly Ziter                                                                                                                                         | 2015     | Oikos                           | [https://onlinelibrary-wiley-com/doi/full/10.1111/oik.02883?casa_token=25Lrxw6w8p0AAAAA%3AyKXztAvEwp8EkwdD3m_ge5iUaOSdvHEzO8t4B2g4-JAiP24LNoN8eklj8hDet9c-QGQs3yIX_9tM1Hfr](https://onlinelibrary-wiley-com.lib-ezproxy.concordia.ca/doi/full/10.1111/oik.02883?casa_token=25Lrxw6w8p0AAAAA%3AyKXztAvEwp8EkwdD3m_ge5iUaOSdvHEzO8t4B2g4-JAiP24LNoN8eklj8hDet9c-QGQs3yIX_9tM1Hfr)       |
