---
title: "Urban Forest Biodiversity Reading List"
editor: visual
---

| **Title**                                                                                                                                 | **Author(s)**                                                                                                                                                  | **Year** | **Journal**                        | **Link**                                                                                                                                                                                                                                                                                                                                                                                              |     |
|-------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------|----------|------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----|
| A review of drivers of tree diversity in suburban areas: Research needs for North American cities                                         | Sophie A. Nitoslawski, Peter N. Duinker, and Peter G. Bush                                                                                                     | 2016     | Environmental Reviews              | <https://cdnsciencepub.com/doi/10.1139/er-2016-0027>                                                                                                                                                                                                                                                                                                                                                  |     |
| A trait-based ecology of the Los Angeles urban forest                                                                                     | D.E. Pataki, H.R. McCarthy, T. Gillespie, G.D. Jenerette, S. Pincetl                                                                                           | 2013     | Ecosphere                          | <http://dx.doi.org/10.1890/ES13-00017.1>                                                                                                                                                                                                                                                                                                                                                              |     |
| Beyond species: functional diversity and the maintenance of ecological processes and services                                             | Marc W. Cadotte, Kelly Carscadden and Nicholas Mirotchnick                                                                                                     | 2011     | Journal of Applied Ecology         | [https://www-jstor-org/stable/41318853](https://www-jstor-org.lib-ezproxy.concordia.ca/stable/41318853)                                                                                                                                                                                                                                                                                               |     |
| The influence of land use type and municipal context on urban tree species diversity                                                      | KS Bourne, TM Conway                                                                                                                                           | 2013     | Urban Ecosystems                   | [https://link-springer-com/article/10.1007/s11252-013-0317-0](https://link-springer-com.lib-ezproxy.concordia.ca/article/10.1007/s11252-013-0317-0)                                                                                                                                                                                                                                                   |     |
| Effects of Urbanization on Tree Species Functional Diversity in Eastern North America                                                     | CA Nock, A Paquette, M Follett, DJ Nowak, C Messier                                                                                                            | 2013     | Ecosystems                         | [https://link-springer-com/article/10.1007%2Fs10021-013-9697-5](https://link-springer-com.lib-ezproxy.concordia.ca/article/10.1007%2Fs10021-013-9697-5)                                                                                                                                                                                                                                               |     |
| LE RÔLE DES INFRASTRUCTURES NATURELLES DANS LA PRÉVENTION DES INONDATIONS DANS LA COMMUNAUTÉ MÉTROPOLITAINE DE MONTRÉAL                   | F Maure, B Rayfield, KT Martins, C Garbe, J Dupras, J Auclair, S Wood, C Messier, M Larocque, A Gonzalez                                                       | 2018     | David Suzuki Foundation            | <https://fr.davidsuzuki.org/publication-scientifique/le-role-des-infrastructures-naturelles-dans-la-prevention-des-inondations-dans-la-communaute-metropolitaine-de-montreal/>                                                                                                                                                                                                                        |     |
| Novel urban ecosystems, biodiversity, and conservation                                                                                    | I Kowarik                                                                                                                                                      | 2011     | Environmental Pollution            | [https://www-sciencedirect-com/science/article/pii/S0269749111000960?via%3Dihub](https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S0269749111000960?via%3Dihub)                                                                                                                                                                                                             |     |
| Promoting and preserving biodiversity in the urban forest                                                                                 | AA Alvey                                                                                                                                                       | 2006     | Urban Forestry & Urban Greening    | [https://www-sciencedirect-com/science/article/pii/S1618866706000732?via%3Dihub](https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S1618866706000732?via%3Dihub)                                                                                                                                                                                                             |     |
| Quantifying biodiversity: procedures and pitfalls in the measurement and comparison of species richness                                   | NJ Gotelli, RK Colwell                                                                                                                                         | 2001     | Ecology Letters                    | [https://onlinelibrary-wiley-com/doi/full/10.1046/j.1461-0248.2001.00230.x](https://onlinelibrary-wiley-com.lib-ezproxy.concordia.ca/doi/full/10.1046/j.1461-0248.2001.00230.x)                                                                                                                                                                                                                       |     |
| The Effects of Human Socioeconomic Status and Cultural Characteristics on Urban Patterns of Biodiversity                                  | AP Kinzig, P Warren, C Martin, D Hope, M Katti                                                                                                                 | 2005     | Ecology & Society                  | <https://www.ecologyandsociety.org/vol10/iss1/art23/>                                                                                                                                                                                                                                                                                                                                                 |     |
| Tree diversity in southern California's urban forest: the interacting roles of social and environmental variables                         | ML Avolio, DE Pataki, TW Gillespie, GD Jenerette, HR McCarthy, S Pincetl, LW Clarke                                                                            | 2015     | Frontiers in Ecology and Evolution | <https://www.frontiersin.org/articles/10.3389/fevo.2015.00073/full>                                                                                                                                                                                                                                                                                                                                   |     |
| Urban tree diversity---Taking stock and looking ahead                                                                                     | J Morgenroth, J Ostberg, C Konijnendijk van den Bosch, AB Nielsen, R Hauer, H Sjoman, W Chen, M Jansson                                                        | 2016     | Urban Forestry & Urban Greening    | [https://www-sciencedirect-com/science/article/pii/S1618866715001557?via%3Dihub](https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S1618866715001557?via%3Dihub)                                                                                                                                                                                                             |     |
| Beyond 'trees are good': Disservices, management costs, and tradeoffs in urban forestry                                                   | Lara A. Roman, Tenley M. Conway, Theodore S. Eisenman, Andrew K. Koeser, Camilo Ordonez Barona, Dexter H. Locke, G. Darrel Jenerette, Johan Ostberg, Jess Vogt | 2021     | Ambio                              | [https://link-springer-com/article/10.1007/s13280-020-01396-8](https://link-springer-com.lib-ezproxy.concordia.ca/article/10.1007/s13280-020-01396-8)                                                                                                                                                                                                                                                 |     |
| Biodiverse cities: the nursery industry, homeowners, and neighbourhood differences drive urban tree composition                           | Meghan L. Avolio, Diane E. Pataki, Tara L.E. Trammell, Joanna Endter-Wada                                                                                      | 2018     | Ecological Monographs              | [https://esajournals-onlinelibrary-wiley-com/doi/full/10.1002/ecm.1290?casa_token=k0vO4QPJw1UAAAAA%3AWxXkh3dDHKnykVUt9vM1mYpUd9bx-fUGbk91LfrOvVjtetQisgFD7Ih2Keluab6chlHXUrMS0EP4YTNm](https://esajournals-onlinelibrary-wiley-com.lib-ezproxy.concordia.ca/doi/full/10.1002/ecm.1290?casa_token=k0vO4QPJw1UAAAAA%3AWxXkh3dDHKnykVUt9vM1mYpUd9bx-fUGbk91LfrOvVjtetQisgFD7Ih2Keluab6chlHXUrMS0EP4YTNm) |     |
| The social production of ecosystem services: A framework for studying environmental justice and ecological complexity in urban landscapes | Henrik Ernstson                                                                                                                                                | 2013     | Landscape and Urban Planning       | [https://www-sciencedirect-com/science/article/pii/S0169204612002861](https://www-sciencedirect-com.lib-ezproxy.concordia.ca/science/article/pii/S0169204612002861)                                                                                                                                                                                                                                   |     |
| The biological deserts fallacy: Cities in their landscapes contribute more than we think to regional biodiversity                         | Erica N Spotswood, Erin E Beller, Robin Grossinger, J Letitia Grenier, Nicole E Heller, Myla FJ Aronson                                                        | 2021     | BioScience                         | [https://academic-oup-com/bioscience/article/71/2/148/6102678?login=true](https://academic-oup-com.lib-ezproxy.concordia.ca/bioscience/article/71/2/148/6102678?login=true)                                                                                                                                                                                                                           |     |
