---
title: "Urban Ecology Reading List"
editor: visual
---

**Note: to access journal articles from off campus, please see the \"Connecting from Off Campus\" section of the library website, here: <https://library.concordia.ca/technology/connect/access.php>.**

**If you are having trouble searching for or accessing academic material from home, please talk to one of the graduate students in the lab, or to Carly, and we can troubleshoot the problem.**

Below, I\'ll list some (mostly recent) papers on urban ecology, biodiversity, and ecosystem services, in no particular order. These papers are useful for showing some of the main directions the field is moving, and the kinds of questions people are asking. There is lots of good stuff in the references, too! You don\'t need to read all of these, but if you have some down time and aren\'t sure what to work on, this is a good activity to improve your urban ecology knowledge.

 **These are papers by authors outside of the lab. For urban ecology papers that Carly (and students/colleagues) have contributed to specifically, you can check find a complete list on the lab website, including access to PDFs: <http://www.carlyziter.com/publications.html> (this will give you a sense of the kind of work we do in the lab)**

-   **Schell CJ, et al. (2020) The ecological and evolutionary consequences of systemic racism in urban environments. Science 57:eaay4497--19**

-   **Knapp S, et al. (2020) A Research Agenda for Urban Biodiversity in the Global Extinction Crisis. BioScience 30:114--12.**

-   **Spotswood EN, et al. (2021) The Biological Deserts Fallacy: Cities in Their Landscapes Contribute More than We Think to Regional Biodiversity. BioScience 15:189--13.**

-   **Grimm, N. B., S. H. Faeth, N. E. Golubiewski, C. L. Redman, J. Wu, X. Bai, and J. M. Briggs. 2008. Global change and the ecology of cities. Science 319:756--760.**

    -   this one is from \~10 years ago, but it\'s a good early overview of urban ecology by one of the pioneers of the field in the US (Nancy Grimm)

-   **Wu J (2014) Urban ecology and sustainability: The state-of-the-science and future directions. Landscape and Urban Planning 125:209--221.**

    -   a nice overview of urban ecology from more of a landscape ecology perspective. Jingle Wu has done great work in landscape ecology, and is a really good thinker

-   **Gaston, K. J., M. L. Ávila-Jiménez, and J. L. Edmondson. 2013. Managing urban ecosystems for goods and services. Journal of Applied Ecology 50:830--840.**

    -   A nice overview of management challenges for urban ecosystem services. Lots still relevant 5 years later. 

-   **Soanes K, et al. (2018) Correcting common misconceptions to inspire conservation action in urban environments. Conservation Biology 33(2):300--306.**

    -   I really like this short paper, addressing some of the common misconceptions about urban areas, and whether they can be important for conservation  

-   **Aronson MF, et al. (2017) Biodiversity in the city: key challenges for urban green space management. Frontiers in Ecology and the Environment 15(4):189--196.**

    -   Nice overview from a management perspective, particularly re: the importance of thinking about scale. I come back to this paper a LOT. Myla Aronson has many other good urban biodiversity articles as well

-   **Lepczyk (2017) Biodiversity in the City: Fundamental Questions for Understanding the Ecology of Urban Green Spaces for Biodiversity Conservation. Bioscience**

    -   Good read alongside the above, lays out some fundamental questions about urban biodiversity

-   **McPhearson T, et al. (2016) Advancing Urban Ecology toward a Science of Cities. BioScience:biw002.**

    -   This one gets a little technical/jargony, and uses a particular framework (ecology \"in, of, and for\" cities), but there are some good research questions/directions listed in here.

-   **Kremer P, et al. (2016) Key insights for the future of urban ecosystem services research. Ecology and Society21(2):art29.**

    -   a good overview of some interesting directions in urban ecosystem services research

-   **Turo KJ, Gardiner MM (2020) The balancing act of urban conservation. Nat Comms:1--5.**

-   "Supplying urban ecosystem services through multifunctional green infrastructure in the United States":[ https://link.springer.com/article/10.1007/s10980-013-9912-y](https://link.springer.com/article/10.1007/s10980-013-9912-y)

-   "Reconnecting Cities to the Biosphere: Stewardship of Green Infrastructure and Urban Ecosystem Services": <https://link.springer.com/article/10.1007/s13280-014-0506-y>

\

