# Andersson_et_al_2015  

Andersson E, McPhearson T, Kremer P, et al (2015) Scale and context dependence of ecosystem service providing units Ecosystem Services 12:157--164 <https://doi.org/10.1016/j.ecoser.2014.08.001>

<https://www.sciencedirect.com/science/article/pii/S2212041614000850?via%3Dihub>

---

Keywords: [ecosystem services](../topics/EcosystemServices.qmd), [urban trees](../topics/UrbanTrees.qmd), [spatiotemporal](../topics/Spatiotemporal.qmd)

Service providing units, landscape - ES connection, SPUs can be situated organisms and/or physical places, spatial [scale](../topics/Scale.qmd) of ES varies, provision of ES varies over time, good table of ecosystem services/scale/SPU/etc., organizational scale affects ES provision, many ES from urban trees are scalable, Fig 1 is of urban tree SPU configurations, ES are dependent on the context that they exist in, require systematic and integrated approaches to ES [management](../topics/Management.qmd)/[planning](../topics/Planning.qmd), "ES must be examined across spatial and temporal scales"
