# Brauman_et_al_2020

Brauman KA, Garibaldi LA, Polasky S, et al (2020) Global trends in nature’s contributions to people. Proc Natl Acad Sci USA 117:32799–32805. https://doi.org/10.1073/pnas.2010473117


<http://www.pnas.org/lookup/doi/10.1073/pnas.2010473117>

---

Keywords: Ecosystem services, [nature's contributions to people](../topics/NaturesContributionstoPeople.qmd), food systems, biodiversity

Declines in nature's contributions have been offset by substituting (e.g. aquaculture instead of wild caught fish) which may mean that humans do not understand the full importance of nature's contributions, nature's contributions can be positive and negative, nature plays a role in providing functions that contribute to wellbeing,  four distinct ways to approach nature's contributions: potential contributions, realized contributions, environmental conditions, and impact on quality of life. Potential contributions declined in majority of categories but ralized contributions and impact on quality of life also declined but were offset by technology changes and socioeconomic conditions. Overall decline in nature's contributions since 1970. Decline in ecosystems' ability to perform regulating functions. Lack of research regarding distribution of nature's benefits.

