# Christin_et_al_2019

Christin S, Hervet É, Lecomte N (2019) Applications for deep learning in ecology. Methods in Ecology and Evolution 10:1632–1644. https://doi.org/10.1111/2041-210X.13256

---

Keywords: [deep learning](../topics/DeepLearning.qmd), [methods](../topics/Methods.qmd), AI, patterns	  

Believe tht deep learning could be useful to ecologists. Machine learning refers to algorithms that can automatically generate predictive models by detecting patterns in data - deep learning is different because it can learn features from data. Deep learning does not require supervision and only requires examples and labels. Current dominant approach to deep learning in ecology is CNN - used for image processing. Deep learning can be used for individual identification, carbon stocks mapping, diversity assessment, count/density estimation, and more. Requires large, labelled training dataset and is especially appropriate when analysing large amounts of data. Provide steps for deep learning and available frameworks. 
