# DesRoches_et_al_2021

Des Roches S, Brans KI, Lambert MR, et al (2021) Socio-eco-evolutionary dynamics in cities. Evolutionary Applications 14:248–267. <https://doi.org/10.1111/eva.13065>


---

Keywords: Urbanization, adaptation, [socioecological](../topics/Socioecological.qmd), [urban evolution](../topics/UrbanEvolution.qmd)	 

Cities are ecosystems built by and for a single species. Good definitions. Urban ecological and evolutionary processes are influenced by social patterns and processes. Little research integrates urban evolutionary biology with eco-evolutionary dynamics and both fields fail to consider how human social processes impact them. Intraspecific and interspecific interactions differ significantly between urban and nonurban habitats. Conceptual diagram for dynamics between social, ecological, and evolutionary patterns and processes. Presence of cities is present in human genes. Artifical selection and other evolutionary adaptations that occurred with humans help us understand evolution and reflect socioeconomic patterns. Evolutionary trait change within species influences population dynamics as well as interactions between organisms and their surroundings, thus affecting ecological patterns and processes. Affluent neighbourhoods can have larger, more diverse and better interconnected green and blue spaces that support more abundant and genetically variable therefore more stable populations of organisms. Burden of disservices is unequally distributed. Use a CHANS approach to studying cities (coupled human and natural systems). Good review.

