# Diaz_et_al_2015

Díaz S, Demissew S, Carabias J, et al (2015) The IPBES Conceptual Framework — connecting nature and people. Current Opinion in Environmental Sustainability 14:1–16. <https://doi.org/10.1016/j.cosust.2014.11.002>

---

Keywords: Nature, IPBES, conceptual, [nature's contributions to people](../topics/NaturesContributionstoPeople.qmd)	

The first public product of the intergovernmental platform on biodiversity and ecosystem services. Designed to develop assessments matched to policy needs and to support capacity building. This is a conceptual framework that IPBES will use moving forward in research that builds off the Millennium Ecosystem Assessment. Six main elements that link people and nature: nature, anthropogenic assets, nature's benefits to people, institutions and governance systems and other indirect drivers, direct drivers, good quality of life. There are different approaches to each of the main elements as well as complex interactions linking them. The processes described occur at multiple scales and management levels. The links between nature and benefits to people are strongly scale-dependent and straddle many scales. Intrinsic values are those inherent to nature independent of human judgement (e.g. non-human species' right to exist) and they have no relationship with possible benefits to humans or their quality of life. Instrumental values are closely associated with the notion of nature's benefits as far as they allow people to achieve a good quality of life. Relational values are imbedded in desirable relationships. Good glossary of relevant terms at the end. 
