# Diaz_et_al_2018

Díaz S, Pascual U, Stenseke M, et al (2018) Assessing nature’s contributions to people. Science 359:270–272. <https://doi.org/10.1126/science.aap8826>

---

Keywords: Nature, IPBES, [[nature's contributions to people]]	  

Nature's contributions to people was built off the Millennium Ecosystem Assessment's use of ecosystem services. NCP recognizes the central and pervasive role that culture plays in defining all links between people and nature and it elevates, emphasizes, and operationalizes role of indigenous and local knowledge. ES research program proceeded largely without benefitting from insights and tools in social sciences and humanities. NCP considered more inclusive and avoids commodifying nature, which is a concern of ES framework. Material contributions are substances or other material elements from nature that directly sustain people's physical existence and material assets. Nonmaterial contributions are nature's effects on subjective or physiological aspects underpinning quality of life - individually and collectively. Regulating contributions are functional and structural aspects of nature that modify environmental conditions. ALl three groups overlap 
