# Dumpelmann_2015

Dümpelmann S (2015) Designing the ‘shapely city’: women, trees, and the city. Journal of Landscape Architecture 10:6–17. https://doi.org/10.1080/18626033.2015.1058560

---

Keywords: Women, [[management]], urban greening, [[gender]]  

Historically, women used street tree planting as an outlet of activism, reform, and design profession. [[street trees]] were a means of empowerment to conquer, reimagine, and construct relationships with the city. Street tree plantings contributed to the creation of a controlled, refined, feminized, and civilized urban environment (thoughts: gentrification? Racism?). At this time, men were thought to hold the knowledge on how to conquer nature and also how to design cities. Cities were viewed as dirty and wild in the post-war modern era. City beautification – or feminization – gained currency when it was realized that it was necessary to create a successful industrial city. Women designers were prominent in designing green parks and fundamental to implementing playgrounds in the US. Women were deemed housekeepers of the community – responsible for beautification of yards, implementation of playgrounds, lobbying for urban parks, and promotion of street tree planting. 
