# Gandy_2022

Gandy M (2022) Urban political ecology: a critical reconfiguration. Progress in Human Geography 46:21–43. https://doi.org/10.1177/03091325211040553

---

Keywords: Eco-criticism, social science, [[urban political ecology]]	 

Determining feature of urban political ecology can be considered the application of a neo-Marxian lens, where urban political ecology was originated within neo-Marxian urban theory. Urban political ecology as a distinct field of study was forming in 1990s and confirmed explicitly in 1996 by Swyngedouw. Urban political ecology can be considered to originate much earlier, if the definition is shifted to include any work of urban environmental research that places social power at the centre of its conceptual frame. First wave of UPE research was underpinned by a focus on links between capital, ecology, and social justice at various scales. UPE remains heavily underrepresented within the global South to this day. **Highlighted Gap: lack of ecology within UPE - we need papers that do ecology with an UPE lens**.  There are questions of nature's agency and spatial scale in UPE - similar to ecology.
