# Gerrish_Watkins_2018b

Watkins SL, Gerrish E (2018) The relationship between urban forests and race: A meta-analysis. J Environ Manage 209:152–168. https://doi.org/10.1016/j.jenvman.2017.12.021

---

Keywords: Meta-analysis, equity, street trees, [racism](../topics/Racism.qmd), [environmental justice](../topics/EnvironmentalJustice.qmd), [luxury effect](../topics/LuxuryEffect.qmd)	 

There are differences in the inequity of the urban forest across studies – is that because the effect differs between cities or is it because of different methodologies.Three major discussions on how different modelling approaches can alter your findings – estimating unconditional or conditional effects, accounting for spatial autocorrelation, and the extent of variation with the unit of analysis. Evidence of inequity can vary by the size of the unit of analysis. Evidence that strength and direction of relationships could vary with the measurement applied. High levels in variation of effect size between studies. When examined alone, there is significant inequity for the Latinx communities and when there are multiple minorities together.  Substantial inequity is found on public land. Adding control variables, detrending for spatial autocorrelation, and using larger scales results in less inequity found. There is a large city effect – relationship with population, residential segregation, and local climate.
