# Goddard_et_al_2021

Goddard MA, Davies ZG, Guenat S, et al (2021) A global horizon scan of the future impacts of robotics and autonomous systems on urban ecosystems. Nat Ecol Evol 5:219–230. <https://doi.org/10.1038/s41559-020-01358-z>


---

Keywords: Robotics, technology, urban ecosystems	

Robotics and autonomous systems (RAS) are technologies that interact with their physical environment (e.g. drones). Technological advances are concurrent with urbanization. We do not know how uptake and deployment of RAS could affect urban biodiversity and ecosystems. People generally were not as worried about RAS concerns than opportunities but did emphasize concerns regarding waste from unrecovered RAS and the quality of RAS-collected data. Differences in responses between Global North and Global South participants. Also differences between environmental and non-environmental expertise participants. RAS could have various negative and/or positive impacts on urban ecosystems - we need to understand better before implementing them widely. Diverse opportunities and challenges of implementing RAS
