# Holden_2012

Holden M (2012) Is Integrated Planning Any More Than the Sum of Its Parts?: Considerations for Planning Sustainable Cities. Journal of Planning Education and Research 32:305–318. https://doi.org/10.1177/0739456X12449483

---

Keywords: Environmental [planning](../topics/Planning.qmd), [sustainable](../topics/Sustainable.qmd) cities, [policy](../topics/Policy.qmd)	

Integration = bringing together multiple elements such that the resulting assemblage has some value that did not exist before. Sustainability is a label of urban planning that accelerates and motivates expectations of integration. Integration can be horizontal (across policy domains) or vertical (across organizations/actors/scales of [governance](../topics/Governance.qmd)). Integration comes from the idea of "holistic government" which identifies that complex, intertwined problems cannot be solved in isolation. There are three levels of integrated policy making - cooperation (low), coordination (medium), integrated policy making (high). To achieve integrated policy making, you need comprehensiveness, aggregation, and consistency. Environmental policy integration (EPI) is a distinct form of integration because it argues that the environment should be present in ALL policy sectors. In practice, integrated planning initiatives face barriers for implementation. We are currently in second-generation thinking of sustainability - recognizing it as a uniquely interdisciplinary problem at every scale: an integrated approach is necessary. Need a diverse group of actors to implement EPI succesfully.
