# Jolivet_Carre_2017

Jolivet V, Carré M-N (2017) Métabolisme urbain et quartiers péricentraux dans la métropolisation. L’exemple du quartier de Saint-Michel à Montréal. Cybergeo: European Journal of Geography. https://doi.org/10.4000/cybergeo.28067

---

Keywords: urban peripheries, [[urban political ecology]], [[governance]], [[urban metabolism]], [[Montreal]]	 

Quarry opened in St-Michael in ~1890s, transformed into a dump in 1968, closed in 2000. Early research on urbanization in MTL focused on the regional decline - during the economic rise of Toronto and reconfiguration of transportation occurring between 1970-2000. Recently the suburbs have become key to the study of urbanization in MTL. Saint-Michel is a multi-ethnic neighbourhood dominated by Haitian and North African communities and recent migrants. There are linear configurations (city discards without reusing resources) and circular configurations (city reuses discarded materials and resources) within urban metabolism theory. Environmental and socio-spatial trajectories of St-Michel are intertwined and inseparable. Quarrying of limestone and clay was a decisive role in the construction of the MTL agglomeration, especially its center. Quarrying left its mark - with most public parks being built on former excavations, although most of these were small (1-10ha). Quarries in St-Michel were 192 and 94 ha - 42% of the surface of the district. They remained active longer than other quarries and provided grey limestone and cement for the construction of large-scale buildings in the modern city. Miron quarry was converted into MTL's main dump and Francon quarry was turned into snow dump site - it is still in operation. The snow dump site impacts the neighbourhood through compromising  safety and air quality - as well as isolating the district by reducing transport. Saint-Michel's population boomed following WW2 - it was described as a new suburb, first attracting quarry workers who wanted to be close to their jobs and then immigrants. 75% of current building stock was constructed 1945-60s to meet the demand for housing - the result was poorly planned urbanization where housing was directly adjacent to industrial areas. The creation of an expressway dividing st-michel in half was experienced as a profound upheaval for residents. The result is an isolated, extremely dense population that has to travel further for services - a neighbourhood in the margins experiencing crisis since the 80s. There has been increase in poverty and unemployment - transformed from a working-class neighbourhood to a disadvantaged neighbourhood in the 80s. Average income is ~ $20,000 less than Montreal's average and 10% of buildings are in disrepair. Extremely important neighbourhood for immigrants. Saint-Michael was annexed to city of MTL in 1968 to try and decrease fragmentation and lead to improved economic (and otherwise) unity. CMM/CUM administration brought together all the cities on hte island of Montreal with the hope of redistributing municipal service costs more equitably - this coincided with reorg of waste management. After annexation, Saint Michel received waste from the entire island of MTL, part of a political strategy to take waste "away from the center", playing an integral role in development of MTL. Since annexation, it has been part of the "urban renewal project". Administration bought quarry from Miron company and made the public decision to transform it into a metropolitan park 1994-2001 (called CESM). The CESM is becoming a showcase of environmental waste management through recycling sites and methane capture. The project means to attract people and bolster MTL's reputation. However, there is a large discrepancy between resident needs/priorities and this project - causing further splintering/fragmentation between htis local space and neighbourhood identity. Saint Michel residents are concerned abut gentrification and lack of consultation. Most educational, recreational, and commercial investments were made in the part of the park that is furthest away from the majority of Saint-Michel residents. 
