# Knapp_et_al_2021  

Knapp S, Aronson MFJ, Carpenter E, et al (2021) A Research Agenda for Urban Biodiversity in the Global Extinction Crisis. BioScience 71:268–279. <https://doi.org/10.1093/biosci/biaa141>


---

Keywords: [biodiversity](../topics/Biodiversity.qmd), urban, ecosystem services	 


Urban growth often occurs in regions of high biodiversity and affects ecosystems past the city's boundaries. Urbanization creates novel species assemblages. Three overarching suggestions for research: broaden geographic focus, broaden taxonomic focus, increase mechanistic understanding. Suggests considering socioecological drivers and including [spatiotemporal](../topics/Spatiotemporal.qmd) dynamics. How do [socioecological](../topics/Socioecological.qmd) factors change across spatial, temporal, and organizational scales. Managing cities for ES will not automatically benefit biodiversity, it may have the opposite effect. Urban areas can be refugia. Spatially explicit approaches and spatiotemporal approaches will allow us to understand why species are distributed across urban areas and derive management plans

