# Landry_et_al_2020

Landry F, Dupras J, Messier C (2020) Convergence of urban forest and socio-economic indicators of resilience: A study of environmental inequality in four major cities in eastern Canada. Landscape and Urban Planning 202:103856. https://doi.org/10.1016/j.landurbplan.2020.103856

---

Keywords: [environmental justice](../topics/EnvironmentalJustice.qmd), [functional diversity](../topics/FunctionalDiversity.qmd), satellite imagery, [canopy cover](../topics/CanopyCover.qmd), [Montreal](../topics/Montreal.qmd)	  

Functional diversity is an effective indicator of resilience – so it is an important factor to consider wrt social inequity in the urban forest. Functional diversity can increase and stabilize production of ES. Included only cities in the mixedwood plains ecozone to make sure diversity is not a function of climate. Tree cover was measured using ESA Sentinel-2 satellite imagery program ([remote sensing](../topics/RemoteSensing.qmd) 10 m x 10 m). Used tree inventories for diversity measurements and census data for socioeconomic. Everything was then scaled to the census tract. CTs with 20 – 100% built surface were selected. Socially vulnerable groups are associated with the built [land cover](../topics/LandCover.qmd) class and opposite the grass, opposite is true for wealth groups. Overall trends are similar across the four urban areas. Diversity is inversely related to social vulnerability.
