# Larouche_et_al_2021

Larouche J, Rioux D, Bardekjian AC, Gélinas N (2021) Urban forestry research needs identified by Canadian municipalities. The Forestry Chronicle 1–10. https://doi.org/10.5558/tfc2021-011

---

Keywords: [Canada](../topics/Canada.qmd), urban forest, [management](../topics/Management.qmd)	

Urban tree [canopy cover](../topics/CanopyCover.qmd) has a much more positive influence on city dwellers than forest trees. Conducted Canada-wide survey in municipalities with 5,000+ people. Binned municipalities based on population size and percentage of canopy/forest cover. 284 responses were received, 200 were valid. Top research need is tree species that are adapted to the urban environment. [Quebec](../topics/Quebec.qmd) especially was interested in impact of trees on rainwater runoff. Third is impact of trees on mental health, then trees and infrastructure, identification of hazardous trees, and control methods for protecting trees from insects and diseases. Small municipalities had different research priorities than all other city sizes, particularly regarding tree inventories. Many canadian municipalities don’t have a tree inventory at all. Most research activities reported by cities were related to pests, tree inventories, good selection of tree species, and invasives. Many needs are highly prolific areas in published research, need to increase knowledge transfer between academics and municipalities. 
