# Luck_et_al_2009

Luck GW, Harrington R, Harrison PA, et al (2009) Quantifying the Contribution of Organisms to the Provision of Ecosystem Services. BioScience 59:223–235. https://doi.org/10.1525/bio.2009.59.3.7

---


Keywords: [[functional diversity]], service providing units, [[provision]]	 

Good def table in intro. Research on contribution of biodiversity to ES is new. Service providing units (SPUs) are species populations that are the fundamental unit contributing ES at the local level. Ecosystem service providers (ESPs) characterize the functional traits and funcitonal importance of organisms that deliver ES. Combined SPUs and ESPs into service provider concept to make a conceptual framework for biodiversity’s contributions to ES.The framework occurs over various organizational levels – promoting linking the most appropriate organizational level to the service. Give examples from the literature for various levels of organizations – populations of one species, multispecies functional groups, landscapes. Understanding/quantifying precise relationships between provider characteristics and beneficiaries is important for land managers who are trying to decide between trade-offs. Relationships between species and groups (synergistic, antagonistic) must be known to understand ES provision. 
