# Mandle_et_al_2021

Mandle L, Shields-Estrada A, Chaplin-Kramer R, et al (2021) Increasing decision relevance of ecosystem service science. Nat Sustain 4:161–169. https://doi.org/10.1038/s41893-020-00625-y

---

Keywords: Well-being, [policy](../topics/Policy.qmd), review	 


Identify five elements that would enable ES research: measure both ES supply and benefit, understand the entire ES chain, measure benefits to capture relevant human values, disaggregate benefits among different groups of people, and include and assess important mediating factors in benefit delivery and valuation. Supply and benefit do not scale linearly most of the time. Understanding how decisions will impact the ecological production function AND the socioeconomic utility function of a service requires understanding the whole chain. The method used to generate metrics of benefits has consequences. Understanding how different groups of people benefit and use ES is necessary for making management decisions that prioritize equity/ [environmental justice](../topics/EnvironmentalJustice.qmd). Changes in ES will affect different people differently based on mediating factors. Most papers valuate ES without actually measuring how much ES is delivered. Rare to disaggregate service benefits based on group and rare to include mediating factors – impossible to meaningfully understand service [delivery](../topics/Delivery.qmd) without these things.
