# Martinez_et_al_2016

Martínez OJA, Fremier AK, Günter S, et al (2016) Scaling up functional traits for ecosystem services with remote sensing: concepts and methods. Ecology and Evolution 6:4359–4371. https://doi.org/10.1002/ece3.2201

---

Keywords: Climate change, [land cover](../topics/LandCover.qmd), [functional traits](../topics/FunctionalTraits.qmd), LiDAR, [remote sensing](../topics/RemoteSensing.qmd)	 

Functional traits are more useful than species for management but are difficult to scale up. Tree species can vary without varying trait composition. Intraspecific trait variation can rival interspecific trait variation. Higher trophic levels impact the trait composition of plants and vice versa. Trait variation across space varies more within than across communities because of redundancy across communities. Human modification can lead to increased trait variation while simultaneously causing homogenization in highly converted lands. Most plant canopy phenological and chemical traits cannot be measured directly from passive remotely sensed data. Structural traits can be mapped with active remote sensing methods (LiDAR).
