# McDonald_et_al_2020  

McDonald RI, Mansur AV, Ascensão F, **Ziter C**, et al (2020) Research gaps in knowledge of the impact of urban growth on biodiversity. Nat Sustain 3:16–24. <https://doi.org/10.1038/s41893-019-0436-6>


---

Keywords: Urban, [biodiversity](../topics/Biodiversity.qmd), growth	 

Focuses on the impact of urban growth on biodiversity. One useful categorization of biodiversity impacts of urban area is direct or indirect. Completed a review on biodiversity papers from 2010-2018. [urban form](../topics/UrbanForm.qmd) and metabolism, which impacts biodiversity, are always changing and are outcomes of human choices. Use the climate change initiative land cover dataset. Table of estimated urban-caused habitat loss for terrestrial biome types - temperate broadleaf forests is highest. Urbanization generally leads to biodiversity declines, especially when expansion occurs on natural habitats. Most research happens in wealthy, temperate biomes even though that is not where the majority of people live. Need more research on indirect effects of urbanization on biodiversity 
