# McPhearson_et_al_2016  

McPhearson T, Pickett STA, Grimm NB, et al (2016) Advancing Urban Ecology toward a Science of Cities. BioScience 66:198–212. <https://doi.org/10.1093/biosci/biw002>


---

Keywords: Urban ecology, conceptual framework	 

Ecology in, of, and for cities. Provides key questions for each domain that are still waiting to be answered. Ecology in cities uses ecological approaches from wild and rural ecosystems in green patches within urban areas - early foundation of the field. [ecology of cities](../topics/EcologyofCities.qmd) incorporates ecology in cities but expands it to assert that the city itself is an ecosystem - increasingly incorporating built infrastructure. Ecology for cities will require bringing research into various modes of practice. The future of urban ecology must be systems focused, interdisciplinary, participatory, [spatiotemporal](../topics/Spatiotemporal.qmd), advance new methods. Defines [urban form](../topics/UrbanForm.qmd). Need cross-city and cross-scale studies to determine general properties and dynamics of urban systems.

