# Ordonez_et_al_2020  

Ordóñez C, Kendal D, Threlfall CG, et al (2020) How Urban Forest Managers Evaluate Management and Governance Challenges in Their Decision-Making. Forests 11:963. <https://doi.org/10.3390/f11090963>


---

Keywords: Urban [planning](../topics/Planning.qmd), green infrastructure, [management](../topics/Management.qmd), [governance](../topics/Governance.qmd)	

We don't understand how local governments make decisions regarding urban forests. Increased densification means this challenge is getting more difficult. Urban forest management is based on ecosystem management.  Urban forest governance and decision making is pressured by a diverse group of needs/goals. Urban development is a conflict in urban forests - although municipalities may be planting more trees, if they are removing old ones for development it creates a homeostasis. Climate change and biodiversity issues are prioritized in urban forest management but are missing crucial details - e.g. impacts of native trees. Used a qualitative and quantitative approach, ranking expert responses. 
