# Ossola_et_al_2021b

Ossola A, Cadenasso ML, Meineke EK (2021) Valuing the Role of Time in Urban Ecology. Front Ecol Evol 9:620620. https://doi.org/10.3389/fevo.2021.620620

---

Keywords: Temporal variation, urban change, development, [[historical]]  

Conceptual diagram of temporal dimensions and processes. Processes occurring in cities are spatially structured but also occur over time. Less empirical resarch on quantifying changes over time in urban environments. Time occurs in a single dimension and only moves forward, however, the duration of events may vary and this has implications for urban ecosystems – i.e. time flows vary and this affects cities spatially and temporally. (A)synchrony can occur in urban ecosystems leading to cascading effects. Research on urban time lags and resiliency is missing – an important factor in determining success of management and conservation. Urban systems that appear stationary at a particular time scale might be non-stationary on a different time scale. Investigating trends in urban systems can reveal how urban ecosystems respond to stressors. Urban ecosystems experience many different cycles that affect the ecosystems – both in their presence and absence. [[legacy effects]] occur from the temporal autocorrelation within and across cities – they are carry-over effects on subsequent events of ecosystems when carrying manifestations of prior events. There are temporal hotspots (urban events happen at a different rate at a specific location compared to similar events at nearby locations) and hot moments (urban events occur more frequently within a particular time period). Future urban events can  be considered along a deterministic-stoichastic gradient.
