# Pham_et_al_2013

Pham T-T-H, Apparicio P, Landry S, et al (2013) Predictors of the distribution of street and backyard vegetation in Montreal, Canada. Urban Forestry & Urban Greening 12:18–27. <https://doi.org/10.1016/j.ufug.2012.09.002>

---

Keywords: Urban vegetation, built environment, [Montreal](../topics/Montreal.qmd), [urban form](../topics/UrbanForm.qmd), [private trees](../topics/PrivateTrees.qmd), [environmental justice](../topics/EnvironmentalJustice.qmd)    

Urban vegetation is unevenly distributed, raising environmental equity concerns. Separate trees/shrubs from lawn and separate public and private vegetation. Used Quickbird satellite images. Neighbourhood age, presence of parks, and distance to city centre are all significant variables in tree models. Presence of detached houses is the most important predictor of tree/shrub [canopy cover](../topics/CanopyCover.qmd). Individual boroughs vary in their vegation composition. Urban vegetation is spatially autocorrelated. Built environment indicators were more important than the sociodemographic variables. Sociodemographic factors were more important for trees than lawns.
