# Pham_et_al_2017

Pham T-T-H, Apparicio P, Landry S, Lewnard J (2017) Disentangling the effects of urban form and socio-demographic context on street tree cover: A multi-level analysis from Montréal. Landscape and Urban Planning 157:422–433

---

Keywords: street trees, [urban trees](../topics/UrbanTrees.qmd), [socioecological](../topics/Socioecological.qmd), tree [canopy cover](../topics/CanopyCover.qmd), [Montreal](../topics/Montreal.qmd), [environmental justice](../topics/EnvironmentalJustice.qmd)	

Street tree canopy provides both ecosystem services and disservices to the population. Urban dwellers across socioeconomic groups highly value and recognize the benefits from trees. The emerald ash borer caused Montreal to cut down 20% of they city's ash trees in 2011. The distribution of the urban forest is generally affected. The distribution of the urban forest is generally affected by three groups of factors: natural, urbn form, vegetation management. Urban density is often less important than urban form. Used street tree cover as dependent variable. Street characteristics, neighbourhood context are groups of independent variables. Number of buildings and percentage of residential buildings have a positive relationship with STC. STC is higher in areas with a lot of immigrants. Urban form is more important than socioeconomic and lifestyle factors. Found equity issues in distribution of STC.
