# Pickett_et_al_2017

Pickett STA, Cadenasso ML, Rosi-Marshall EJ, et al (2017) Dynamic heterogeneity: a framework to promote ecological integration and hypothesis generation in urban systems. Urban Ecosyst 20:1–14. <https://doi.org/10.1007/s11252-016-0574-9>


---

Keywords: Urban, spatial [heterogeneity](../topics/Heterogeneity.qmd), [spatiotemporal](../topics/Spatiotemporal.qmd), community	  


Patterns and processes in spatially heterogeneous and temporally dynamic mosaics such as cities are of interest - shown by the term dynamic heterogeneity. Extreme levels of biotic and biophysical heterogeneity within cities. There is also socioeconomic heterogeneity. Cities can produce heterogeneity as an outcome due to temporal changes. Heterogeneity can appear at all spatial scales within a city and across cities. Human ecosystems are biotic, physical, social, and built hybrids. Provide hierarchial structure for the framework. Uses urban watersheds as a case study. Urban systems are heterogeneous with different layers of heterogeneity, the layers of heterogeneity interact at various scales, and the interaction produces new heterogeneity. 
