# Qiu_et_al_2018

Qiu J, Carpenter SR, Booth EG, et al (2018) Understanding relationships among ecosystem services across spatial scales and over time. Environmental Research Letters 13:1–16


---

Keywords: [socioecological](../topics/Socioecological.qmd), future, tradeoffs, forecasting	

Humans have transformed our biosphere to promote ES but at the cost of other, less prioritized ES that are equally important. Provisioning services are increasing while [regulating ecosystem services](../topics/RegulatingEcosystemServices.qmd) are declining. Tradeoffs, synergies, and constraint effects (one ES imposes upper limits on another ES). Cannot just extrapolate ES levels from one scale to another. Ecological processes and human management are mismatched in [spatiotemporal](../topics/Spatiotemporal.qmd) scale. Used Agro-IBIS to quantify ES. Use different future scenarios to produce spatiotemporal changes of major drivers. Used 3 spatial scales and predicted outcomes over time. Relationships between ES differed at spatial and temporal scales, as well as between different ES. ES relationships were not static over time. Biophysical connections underlying interactions between ES can be scale dependent. Dominant drivers that control multiple ES can vary in magnitude across scales, altering ES relationships. ES relationships can also change due to artificial scale effects based on the spatial extent of analysis. Conceptual diagram showing how changes in [scale](../topics/Scale.qmd) affect ES. 
