# Renard_et_al_2015

Renard D, Rhemtulla JM, Bennett EM (2015) Historical dynamics in ecosystem service bundles. Proc Natl Acad Sci USA 112:13411–13416. https://doi.org/10.1073/pnas.1502565112

---

Keywords: Temporal, ES, [historical](../topics/Historical.qmd)	

Analyze 9 ES at five-year intervals from 1971 – 2006 to show how a [spatiotemporal](../topics/Spatiotemporal.qmd) approach can enhance our understanding of ES dynamics. Time is just as important as space in ES processes and services. Understanding multiple ES and their synergies, trade-offs, and interactions is crucial. Used ES-bundle approach – ES bundle is mix of positively correlated ES provided in the same place and time. Provision of each service changed significantly over time and mean provision increased for almost every service, [cultural ecosystem services](../topics/CulturalEcosystemServices.qmd) showed greatest magnitude of change through time. The most common types of ES bundles and their spatial dstribution changed through time. Spatial distribution of ES bundles was related to biophysical and socioeconomic attributes of the region. At the regional [scales](../topics/Scale.qmd), relationships among ES changed through time in type and strength of relationship. Demonstrated that provision of ES and relationships are dynamic through time and space – trajectories through time are not uniform and are related to spatial distribution of environmental, social, and economic characteristics. Relationships between services can shift through time. Show that ES maps change through time and political decisions and local factors interact to shape changes. 
