# Roman_et_al_2018

Roman LA, Pearsall H, Eisenman TS, et al (2018) Human and biophysical legacies shape contemporary urban forests: A literature synthesis. Urban Forestry & Urban Greening 31:157–168. <https://doi.org/10.1016/j.ufug.2018.03.004>


---

Keywords: [historical](../topics/Historical.qmd) ecology, [socioecological](../topics/Socioecological.qmd), urban	  


Trees were not a prominent part of cities until the mid 1800s. Using today's socioeconomic statistics to evaluate urban trees ignores the lag time between tree planting and maturation. Current vegetation cover can be predicted by socioeconomic data from several decades prior. There are human and biophysical [legacy effects](../topics/LegacyEffects.qmd) to current tree cover in cities. Bioregional context determines starting conditions of urban forests and their development. Some trees have historical cultural significance in certain time periods and that has a legacy effect due to increased planting during that time period - e.g. widespread planting of Acer trees in Canada due to symbolism. The first urban tree movement in the US started in the 19th century with higher urbanized populations and associated health concerns - still leaves legacies to this day. Canada often used the US as inspiration for tree planting in their cities. Suburban areas expanded in mid-20th century in Canada. Building age often correlates with tree cover in a nonlinear way. Ecological disturbance causes legacy effects.
