# Roman_et_al_2017

Roman LA, Fristensky JP, Eisenman TS, et al (2017) Growing Canopy on a College Campus: Understanding Urban Forest Change through Archival Records and Aerial Photography. Environmental Management 60:1042–1061. https://doi.org/10.1007/s00267-017-0934-0

---

Keywords: Temporal, [historical](../topics/Historical.qmd), sampling [methods](../topics/Methods.qmd), urban, [canopy cover](../topics/CanopyCover.qmd), [academia](../topics/Academia.qmd)	 

Urban canopy cover is determined by past events due to the time lag in tree maturation and canopy development. General model for tree cover in cities is increasing over time in grassland areas and decreasing over time in forested areas. Used college campus to investigated how urban forest changed over 150 years. College campuses set canopy cover goals and measure ES internally, much like how a municipality manages the urban forest. Used mixed methods – classified and investigated different time segments using archival records, aerial imagery, news clippings, Trustees minutes. Several decades are needed to fully realize ambitious plans to increase the extent of urban forest. Combining tree age classes is important for maintaining consistent canopy cover. Trees, gardens, and landscape design are used to indicate status and wealth – which is why universities are okay with dedicating time and money to canopy cover. Highlight connections to four broad movements: urban parks; City Beautiful; “spaces in between”, and urban sustainablility.
