# Spotswood_et_al_2021

Spotswood EN, Beller EE, Grossinger R, et al (2021) The Biological Deserts Fallacy: Cities in Their Landscapes Contribute More than We Think to Regional Biodiversity. BioScience biaa155. https://doi.org/10.1093/biosci/biaa155

---

Keywords: Urban, [[biodiversity]], conservation	 

Cities are placed intentionally and often start out quite different than their surroundings - development furthers these differences. Cities have novel trophic assemblages. The benefit of species entering the city depends on the development of the land surrounding the city and how hospitable it is. Urbanization alters abiotic and biotic conditions. Resource availability and habitat quality within cities shifts over time based on human preferences/behaviour and infrastructure age.  More closely related species tend to respond similarly to urbanization. Cities can sometimes provide food and water resources not offered in the surroudning landscape during times of stress. Cities can increase regional habitat [[heterogeneity]]. Cities can be used as stopover sites on migration routes. Cities can contribute to species' genetic diversity and preadaptation to climate change. Cities can enable and bolster intensive engagement and stewardship. 
