# Sutherland_et_al_2018

Sutherland IJ, Villamagna AM, Dallaire CO, et al (2018) Undervalued and under pressure: A plea for greater attention toward regulating ecosystem services. Ecological Indicators 94:23–32. https://doi.org/10.1016/j.ecolind.2017.06.047

---

Keywords: Ecological [pressure](../topics/Pressure.qmd), [regulating ecosystem services](../topics/RegulatingEcosystemServices.qmd), indicators	

Use [spatiotemporal](../topics/Spatiotemporal.qmd) contexts of ES to illustrate the benefits of regulating ES using a watershed perspective. ES indicators must be spatially and temporally explicit. Undervaluation of regulating ES can lead to management trade-offs that create risk for human safety and can cause delayed impacts on cultural and provisioning ES. Loss of regulating ES is often masked by technological substitutes but these are reactive not proactive measures. Capacity, demand, and pressure are distinct things to measure for regulating ES. Capacity and demand for regulating ES changes over space and time. ES capacity should be defined as functional units that are spatially and temporally explicit, scalable, and quantifiable. Intensity, duration, anad frequency of a pressure influence the need for regulating ES (pulse vs press). Shows non-linear relationships between disturbance types and regulating ES capacity.
