# Tatsumi_et_al_2021

Tatsumi S, Iritani R, Cadotte MW (2021) Temporal changes in spatial variation: partitioning the extinction and colonisation components of beta diversity. Ecology Letters 24:1063–1072. https://doi.org/10.1111/ele.13720

---

Keywords: Community assembly, [[spatiotemporal]], [[heterogeneity]], [[biodiversity]]	

Human forces cause community diassembly and reassembly at unprecedented rates, leading to reductions in spatial variation and therefore increased homogeneity. Extirpation in specific regions can result in increased heterogeneity. Colonization often results in increased homogeneity due to common species across sites but if a species only colonizes specific spots, it can also lead to heterogeneity. Developed a new analytical method to partition the net temporal change in beta diversity into components that reflect species extirpations and colonisations. Spatial extension of Legendre 2019. Show case studies of use. Could potentially use it to determine the rate of homogenization of different cities/parks. Not sure if it works in an urban setting due to planting, however. 
