# Tomscha_et_al_2016

Tomscha SA, Sutherland IJ, Renard D, et al (2016) A Guide to Historical Data Sets for Reconstructing Ecosystem Service Change over Time. BioScience 66:747–762. https://doi.org/10.1093/biosci/biw086

---

Keywords: Landscape, ecosystem services, [historical](../topics/Historical.qmd), [legacy effects](../topics/LegacyEffects.qmd), sampling [methods](../topics/Methods.qmd)	  

Historical datasets present an important opportunity to explore the temporal dynamics of ES. The study of historical ES has many challenges including data scarcity, data inconsistency, indicator inconsistency, and lack of guidance. When historical data is ignored, we get inappropriate baseline knowledge, miss legacy effects and time lags, lack understanding of environmental inequity, and overlook what we have gained. Measure ES capacity, flows, and demand. Tree rings posess great potential for understanding ES capacity for provisioning  and regulating services. Historical maps and cadastral surveys can provide ES baselines prior to remote sensing. Aerial photographs provide high resolution, spatially explicit reconstructions. Satellite imagery provides temporally frequent and spatially extensive biophysical information. Chronosequences measure ecosystem properties at ecologically similar sites with differing time-since-disturbance or successional gradients and can track slow changes in ES capacity. Historical maps and surveys can help identift locations for ES demand. Census data underpin drivers of ES demand. ES flows can cover great distances, meaning supply and demand can be spatially mismatched. Provides tables and figures of datasets and potential uses. 
