# Uchida_et_al_2021

Uchida K, Blakey RV, Burger JR, et al (2021) Urban Biodiversity and the Importance of Scale. Trends in Ecology & Evolution 36:123–131. https://doi.org/10.1016/j.tree.2020.10.011

---

Keywords: Urban [biodiversity](../topics/Biodiversity.qmd), [scale](../topics/Scale.qmd), spatial	 

Eco-evolutionary and human cultural processes scale nonlinearly with city size. Currently a lack of comprehensive understanding of how ecological and evolutionary processes change with city size. To conserve urban biodiversity we must understand relationship between city scale and biodiversity. Management for biodiversity will look very different between small cities and megacities, the same approaches and funding do not work the same way. Unique pressures from the urban environment will influence eco-evolutionary processes in unpredictable ways. Patterns of biodiversity seen in “nature” may also apply to certain urban areas. Biodiversity scaling with city size will influence management in two ways: goal-setting and efficacy/implementation of management. Large cities have the opportinity to protext threatened species over a broader geographic scales but also cause the spread of invasive species due to trade networks. Scale changes the outcome of similar management outcomes. Scaling is relevant t [private trees](../topics/PrivateTrees.qmd). 
