# Villamagna_et_al_2017

Villamagna AM, Mogollón B, Angermeier PL (2017) Inequity in ecosystem service delivery: socioeconomic gaps in the public-private conservation network. E&S 22:art36. https://doi.org/10.5751/ES-09021-220136

---

Keywords: [socioecological](../topics/Socioecological.qmd), hydrological, well-being, [environmental justice](../topics/EnvironmentalJustice.qmd), [racism](../topics/Racism.qmd)	  

Number of beneficiaries, their identity, and magnitude of benefits are largely unknown for majority of conservation areas. Questions of social environmental justice should expand to include the disproportionate distribution of benefits from public CAs. Incorporating ES into analyses re: equity concerns requires an objective, repeatable measurement technique. Provide discussion and demonstration of mapping nonhydrological services in the appendices. POC are underserved by hydrological benefits conveyed from CAs, particularly from federal. Privately producing ES benefits on your land requires dispensable income and therefore inherently favours the wealthy. 
