# Wang_et_al_2021

Wang X, Dallimer M, Scott CE, et al (2021) Tree species richness and diversity predicts the magnitude of urban heat island mitigation effects of greenspaces. Science of The Total Environment 770:145211. https://doi.org/10.1016/j.scitotenv.2021.145211

---

Keywords: [[temperature mitigation]], land surface temp, [[Landsat]]	  

Urbanization and global warming are happening concurrently - with the emergence of urban heat islands. Urbanization changes absorption of solar radiance which leads to higher temperatures in urban areas compared to rural. UHIE increases pollution through artificial cooling and increases mortality. Greenspaces reduce the UHIE. Greenspace structure affects ability to mitigate UHIE - change structure when building more greenspaces is not an option. Calculated land surface temperatures using remote sensing. Cooling range correlated with mean crown width and tree density in summer. TDA correlated with tree density, tree coverage, [[biodiversity]], [[canopy cover]], and richness in spring and summer. Cooling effects vary seasonally.
