# Wong_et_al_2020

Wong C, Ballegooyen K, Ignace L, et al (2020) Towards reconciliation: 10 Calls to Action to natural scientists working in Canada. FACETS 5:769–783. https://doi.org/10.1139/facets-2020-0005

---

Keywords: [[reconciliation]], ITK, ethics, [[Indigenous knowledge]]	  

Outline 10 calls to action to natural scientists to enable reconciliation. Natural scientists often fail to see the link between their work and Indigenous communities. Indigenous communities are underrepresented in STEM, especially at the graduate level. 1 – natural scientists must understand the socio-political landscape around their research sites. 2 – generating knowledge about the land is a goal shared with Indigenous peoples, therefore we must seek meaningful relationships and collaboration. 3 – Enable knowledge sharing and co-production. 4 – NS studying animals should seek out advice from Elders for respectful ways of handling animals. 5 – provide meaningful opportunities for Indigenous community members, particularly youth, to participate in science. 6 – incorporate Indigenous place names as permitted. 7 – take a course on Indigenous history and rights.  8 – change approaches to funding. 9 – editors need to recognize that publication of research on ITK requires review and permission from respective Indigenous communities. 10 – call on NS and institutions to develop a new vision for conducting natural science: fundamentally mainstreaming reconciliation in all aspects of the scientific endeavor. True reconciliation requires going beyond what is required.
