# WrightWendel_et_al_2012

Wright Wendel HE, Zarger RK, Mihelcic JR (2012) Accessibility and usability: Green space preferences, perceptions, and barriers in a rapidly urbanizing city in Latin America. Landscape and Urban Planning 107:272–282. https://doi.org/10.1016/j.landurbplan.2012.06.003


---

Keywords: Green space, safety, [gender](../topics/Gender.qmd), Global South, [environmental justice](../topics/EnvironmentalJustice.qmd)	  

Improving access to green space provides a means for improving equality within urban areas. Neighbourhood [parks](../topics/Parks.qmd) were often much smaller and had less amenities than larger “urban parks”. Men consistently used green spaces more than women, for all demographic user groups. Sports fields dominated green spaces and were underused by women and the elderly. Size of green space was very important for users of urban parks, whereas neighbourhood parks were used for daily life activities like cooking and playing. Safety was primary barrier for using green spaces, especially for women. 
