# Zhang_et_al_2019

Zhang Y, Middel A, Turner BL (2019) Evaluating the effect of 3D urban form on neighborhood land surface temperature using Google Street View and geographically weighted regression. Landscape Ecol 34:681–697. https://doi.org/10.1007/s10980-019-00794-y


---

Keywords: [Google Street View](../topics/GoogleStreetView.qmd), land surface, urban heat island, [temperature mitigation](../topics/TemperatureMitigation.qmd)   

Land surface temperatures can be accessed from remote imagery in a fine-scale way – they are related to canopy layer air temperature but the relationship is non-linear. LST was derived from ASTER data at a 90-m resolution. GSV was used to create spherical land-cover fractions. 1-m [[land cover]] map with 6 classes was obtained from aerial photos provided by NAIP. Soil and building fractions are positively associated with LST during the day and negatively at night. Spherical fractions explain more variation than planar for LST. Heterogeneity in vertical form results in shading heterogeneity and can significantly effect LST. Daytime models have a better fit than nighttime models. SD of spherical fractions are negatively correlated with LST – denser and heterogeneous urban forms can effectively reduce daytime heat.
