# Ziter_et_al_2017

Ziter C, Graves RA, Turner MG (2017) How do land-use legacies affect ecosystem services in United States cultural landscapes? Landscape Ecol 32:2205–2218. https://doi.org/10.1007/s10980-017-0545-4

---

Keywords: [[historical]], agriculture, urban, [[land cover]], [[legacy effects]]	

Historical land use effects on ES can change over time. Three conditions where land-use legacies are especially important for understanding current ES supply: intrinsically slow ecological processes govern ES supply, time lags between land-use change and ecosystem responses delay the effects on ES supply, threshold relationships exist so that changes in ES may be difficult to reverse. Soil ES, environmental pollutants are example of slow ecological processes governing ES. Time lag effects can be especially pronounced for biodiversity-based services (e.g. exinction debts) and hydrologic services. Studies have not yet addressed thresholds and reversibility related to land-use legacies. Hydrologic ES, soil P levels,  flood mitigation are examples of ES that experience historical thresholds and legacy lock-ins. Long-term consequences of new contaminants may provide unaticipated challenges for future ES supply (e.g. microplastics)
