# Ziter_Turner_2018

Ziter C, Turner MG (2018) Current and historical land use influence soil-based ecosystem services in an urban landscape. Ecological Applications 28:643–654. https://doi.org/10.1002/eap.1689

---

Keywords: [carbon storage](../topics/CarbonStorage.qmd), ES, [historical](../topics/Historical.qmd), [land cover](../topics/LandCover.qmd) 	 

Urban areas are temporally heterogeneous on a fine scale – often urban areas expand and take over previously agricultural land, making them ideal for studying land-use legacies. Land cover based proxies are poor tool for measuring ES – cities are too heterogeneous. Need to understand which ES indicators vary among and within land-cover classes. Historical land-use affects ecosystem functions for decades to millennia. ES related to soil may be particularly sensitive to temporal impacts. Measured soil characteristics on previously agricultural land to see legacy effect on C storage, water quality, and runoff. Soil C varied with time since development but relationship differed among land cover classes and with depth. Soil properties varied with time since development, indicating that land-use legacies can influence current urban ES. There were differences among land cover classes in the spatial scales at which variance in soil properties was most pronounced – most likely due to management.
