---
title: "Census Data"
editor: visual
---

The most recent census data (2021) are linked here, but all previous census data are available in the archives (e.g., 2016, 2011, etc.)

| Dataset                   | Organization      | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | Date | File Format        | Link                                                                                                         |
|-----------|-----------|------------------|-----------|-----------|-----------|
| 2021 Census of Population | Statistics Canada | Comprehensive download files include counts and rates for all                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                 geographies within a specific geographic hierarchy and for all available                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                 topics.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | 2021 | CSV, TAB, IVT      | <https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/details/download-telecharger.cfm?Lang=E>     |
| 2021 Boundary Files       | Statistics Canada | Digital and cartographic boundary files for provinces/territories, census divisions, federal electoral districts, census subdivisions, designated places, census forward sortation areas (FSA), economic regions, census agricultural regions, census consolidated subdivisions, census metropolitan areas and census agglomerations, census tracts, population centres, dissemination areas, dissemination blocks, aggregate dissemination areas, population ecumene, agricultural ecumene | 2021 | SHP, GML, GDB, WMS | <https://www12.statcan.gc.ca/census-recensement/2021/geo/sip-pis/boundary-limites/index2021-eng.cfm?year=21> |

## 
