---
title: "Road Data"
editor: visual
---

There are various sources of road data across Canada. Some of the most useful sources for the ZULE Lab are listed below:

| Dataset                         | Organization      | Description                                                                                                                       | Date                           | File Format        | Link                                                                                                |
|------------|------------|-------------|------------|------------|------------|
| Road Network File (Canada-wide) | Statistics Canada | Includes the unique identifier, DGUID, name and type for each side of a                                                           
                                                       street arc (where applicable) for provinces and territories, and census                                                            
                                                       subdivisions. In the 2021 Census Road Network File, streets are ranked                                                             
                                                       according to five levels of detail, suitable for mapping at small to                                                               
                                                       medium scales.                                                                                                                     | 2021 (previous years archived) | SHP, GML, GDB, WMS | <https://www12.statcan.gc.ca/census-recensement/2021/geo/sip-pis/rnf-frr/index2021-eng.cfm?year=21> |
| Complete Road Assets            | City of Montreal  | Road assets (pavements, islands, intersections, sidewalks, curbs) with a spatial representation and various attached information. | Ongoing                        | CSV, SHP, GeoJSON  | <https://donnees.montreal.ca/ville-de-montreal/voirie-actif>                                        |
| Roadways and Intersections      | City of Montreal  | Roadways and intersections of Montreal (does not include other road assets)                                                       | Ongoing                        | CSV, SHP, GeoJSON  | <http://donnees.ville.montreal.qc.ca/dataset/voirie-chaussee-intersection>                          |
| Sidewalks and Traffic Islands   | City of Montreal  | Sidewalks and traffic islands of Montreal (does not include other road assets)                                                    | Ongoing                        | CSV, SHP, GeoJSON  | <http://donnees.ville.montreal.qc.ca/dataset/voirie-trottoir-ilot>                                  |
| Off-Road Zones                  | City of Montreal  | Off road zones of Montreal (does not include other road assets)                                                                   | Ongoing                        | CSV, SHP, GeoJSON  | <http://donnees.ville.montreal.qc.ca/dataset/voirie-zone>                                           |
| Bike Paths                      | City of Montreal  | Bike paths of Montreal (does not include other road assets)                                                                       | Ongoing                        | CSV, SHP, GeoJSON  | <http://donnees.ville.montreal.qc.ca/dataset/pistes-cyclables>                                      |
| Road Structures                 | City of Montreal  | Road structures of Montreal (does not include other road assets)                                                                  | Ongoing                        | CSV, SHP, GeoJSON  | <https://donnees.montreal.ca/dataset/structure-routiere>                                            |
| Road Projects                   | City of Montreal  | Road projects of Montreal (does not include other road assets)                                                                    | Ongoing                        | CSV, SHP, GeoJSON  | <http://donnees.ville.montreal.qc.ca/dataset/schema-transport>                                      |

: \
