---
title: "Boundary Data"
editor: visual
---

There are various sources of boundary data, depending on scale you are interested in. If you ever want general datasets openly available within R, you can use the package `osmdata` to pull administrative boundaries straight from Open Street Map. Statistics Canada, the city of Montreal, Quebec, and Canadian governments all have boundary data as well.

| Dataset                                               | Organization                           | Description                                                                                                                                                                                                                                                                                           | Date | File Format       | Link                                                                                                                  |
|------------|------------|------------|------------|------------|------------|
| Boundary Files                                        | Statistics Canada                      | There are two types of boundary files: cartographic and digital. Cartographic boundary files portray the geographic areas using only the major land mass of Canada and its coastal islands. Digital boundary files portray the full extent of the geographic areas, including the coastal water area. | 2021 | SHP, GML, TAB     | <https://www12.statcan.gc.ca/census-recensement/2021/geo/sip-pis/boundary-limites/index2021-eng.cfm?year=21>          |
| Neighbourhood Boundaries                              | City of Montreal                       | Polygons delimiting the boroughs of the City of Montreal, boroughs and related cities constituting the Montreal agglomeration.                                                                                                                                                                        | 2023 | GeoJSON, SHP, KML | <http://donnees.ville.montreal.qc.ca/dataset/polygones-arrondissements>                                               |
| Large Parks                                           | City of Montreal                       | Montreal's 24 large parks, including 11 parcs-nature                                                                                                                                                                                                                                                  | 2023 | SHP, GeoJSON, KML | <http://donnees.ville.montreal.qc.ca/dataset/grands-parcs>                                                            |
| Large Parks, Borough Parks and Public Spaces          | City of Montreal                       | This dataset represents all the parks and public spaces identified and illustrates their surface polygons in the context of the urban fabric of the territory. The data is not representative of linked city parks, which are only partially represented.                                             | 2023 | SHP, GeoJSON, KML | <https://donnees.montreal.ca/ville-de-montreal/grands-parcs-parcs-d-arrondissements-et-espaces-publics>               |
| Vacant Spaces                                         | Communauté Métropolitaine de Montréal  | Delimitation of vacant spaces to redevelop in Montreal and Longueuil                                                                                                                                                                                                                                  | 2023 | SHP, GeoJSON, KML | <http://cmm.qc.ca/donnees-et-territoire/observatoire-grand-montreal/produits-cartographiques/donnees-georeferencees/> |
| Green Spaces                                          | City of Montreal                       | Public areas with vegetation cover: gardens, playgrounds, resting areas, sports facilities, etc.                                                                                                                                                                                                      | 2023 | SHP, GeoJSON, KML | <http://donnees.ville.montreal.qc.ca/dataset/schema-environnement-milieux-naturels>                                   |
| Water bodies on the Island of Montreal                | City of Montreal                       | Streams, brooks and lakes of Montreal                                                                                                                                                                                                                                                                 | 2023 | SHP, GeoJSON, KML | <https://donnees.montreal.ca/ville-de-montreal/limites-cours-eau>                                                     |
| Woods and Forest Corridors                            | City of Montreal                       | Woods and forest corridors identified by the Communauté métropolitaine de Montréal (CMM)                                                                                                                                                                                                              | 2023 | SHP, GeoJSON, KML | <https://donnees.montreal.ca/ville-de-montreal/schema-environnement-milieux-naturels>                                 |
| Community Gardens                                     | City of Montreal                       | Vegetable gardens attributed to and cultivated by citizens or families                                                                                                                                                                                                                                | 2023 | SHP               | <http://donnees.ville.montreal.qc.ca/dataset/jardins-communautaires>                                                  |
| Wood                                                  | City of Montreal                       | Natural wastelands of Montreal obtained by aerial photography, field visits and studies                                                                                                                                                                                                               | 2023 | SHP, GeoJSON, KML | <http://donnees.ville.montreal.qc.ca/dataset/bois>                                                                    |
| Brownfields                                           | City of Montreal                       | This dataset contains polygons delineating the natural wastelands in the Greater Montreal area.                                                                                                                                                                                                       | 2021 | SHP, GeoJSON, KML | <https://donnees.montreal.ca/ville-de-montreal/frichenaturelle#resource-friche_naturelle_en_format_shapefile>         |
| Current and Soon-to-Be Protected Natural Environments | City of Montreal                       | Current and soon-to-be protected natural areas, excluding water bodies under jurisdiction of the governments of Quebec and Canada                                                                                                                                                                     | 2021 | SHP, GeoJSON, KML | <https://donnees.montreal.ca/ville-de-montreal/milieu-naturel-protege>                                                |
| Ecoterritories                                        | City of Montreal                       | Ten ecoterritories of more than 15 ha of protected, urban and natural areas requiring further protection and promotion                                                                                                                                                                                | 2021 | SHP, GeoJSON, KML | <https://donnees.montreal.ca/ville-de-montreal/ecoterritoires>                                                        |
| Open Data                                             | Canada Federal Government              | Open data portal for federal level data                                                                                                                                                                                                                                                               |      | All               | <https://open.canada.ca/en/open-data>                                                                                 |
| Open Data                                             | Quebec Federal Government              | Open data portal for provincial level data                                                                                                                                                                                                                                                            |      | All               | <https://www.donneesquebec.ca/>                                                                                       |
