# Lab Code of Conduct and Policies

*Code of conduct [adapted](https://github.com/BahlaiLab/Policies/blob/master/Code_of_conduct.md) from our colleague [Dr. Christie Bahlai](https://bahlailab.org/), Kent State University*

Science is hard, and the work of making sure science isn't harder than it needs to be is on all of us. We create our culture, and in the Ziter lab, our culture is inclusive.

We value the participation of every member of our community and want to ensure that every lab member and collaborator has a positive, educational experience unhindered by unnecessary challenges caused by non-inclusive behaviour. Accordingly, everyone who participates in any Ziter Lab project is expected to show respect and courtesy to other community members at all times, and recognize that you are an ambassador for our lab and institution when interacting with collaborators, community partners, or other stakeholders/rightsholders.

[Carly Ziter](carlyziter.com), as head of the Ziter Lab, and all lab members, are dedicated to *a harassment and discrimination-free experience for everyone*. Discrimination or harassment based on racial or ethnic background, citizenship status, religion (or lack thereof), political affiliation, gender identity/expression, sexual orientation, dis/ability status, appearance or body size will not be tolerated. We do not tolerate harassment or discrimination by (and/or of) members of our community in any form.

To make clear what is expected, we ask all members of the community to conform to the following Code of Conduct. - All lab communication - online and in person - should be appropriate for a professional audience including people of many different backgrounds. Sexual or discriminatory language and imagery is not appropriate at any time. - Be kind to others. Do not insult or put down other contributors. - Behave professionally. Remember that harassment and sexist, racist, or exclusionary jokes are not appropriate. - Please make an effort to make an inclusive environment for everyone. Give everyone a chance to talk and an opportunity to contribute. - Watch out for [microaggressions](https://en.wikipedia.org/wiki/Microaggression). *Be aware that your actions can be hurtful to others or contribute to a negative environment even if you had no intent of harm*. Listen. Offer a genuine apology. Commit to learning and doing better.

Unacceptable behaviour includes:

-   offensive verbal comments related to gender, sexual orientation, disability, physical appearance, body size, race, religion (or lack thereof)

-   sexual images in public spaces

-   deliberate intimidation

-   stalking

-   following

-   harassing photography or recording

-   sustained disruption of discussions

-   inappropriate physical contact

-   and unwelcome sexual attention.

*Participants asked to stop any harassing or discriminatory behaviour are expected to comply immediately.*

Members of the community who violate these rules - no matter how much they have contributed to the Ziter lab, or how specialised their skill set - will be approached by Carly Ziter.

To report an issue please contact [Carly Ziter](https://www.carlyziter.com/contact-us.html). All communication will be treated as confidential.

## Additional Lab Policies 

### Flexible working hours 

For post-graduate members of the lab (***grad students and PDFs***), the specific hours that you choose to work are up to you. Some people find they work best on certain tasks early in the morning, or late at night. Some members prefer to work part time from a coffee shop or home. This flexibility is a major perk of academia, and it is the policy of the Ziter Lab that every member is already self-motivated and doesn't necessarily need to work a traditional 9 to 5 day from the lab in order to meet their goals. *However, ideally, all lab members will have at least a few hours most days to overlap with Carly and/or other lab members in order to stay in touch on any challenges or successes, and contribute to the intellectual and social culture of the lab.*

***Undergraduate research assistants*** should check in with Carly as well as their direct graduate or postdoc advisor about work hours (see the undergrad orientation document in Google Drive). Some project positions will require specific hours, while others are more flexible. Undergraduates in the lab are encouraged to attend lab meetings and participate in the broader activities of the lab.

***All lab members*** are expected to participate in scheduled lab meetings when possible. If you anticipate working particularly unusual hours (regularly, or during a specific period), please touch base with Carly so that we’re on the same page.

Along these lines, we are each welcome to send work-related emails over the weekend or late at night, but no lab members are required to reply to them outside of their typical work hours (even if the email is from Carly – who tends to send late night emails!)

### Vacation 

***Scheduled time off and vacations are important for personal health, well-being, and workplace productivity.*** Note that Concordia does not yet have an official policy on vacation leave for graduate students. As such, please consider this McGill policy for graduate student vacation as a rough guide if you are unsure what is appropriate, or, talk to Carly:

> “Graduate students and postdocs should normally be entitled to vacation leave equivalent to university holidays and an additional total of fifteen (15) working days in the year.”
>
> Short vacations (e.g. a few days) do not need to be cleared with Carly in advance, although I do appreciate knowing when you are away.
>
> For vacations of a longer period (e.g. a week or more), the timing should ideally be discussed with Carly in advance so that we can ensure that your absence doesn’t compromise planned research, lab, or classroom activities, and we can find someone to step in and cover your responsibilities if necessary.

*Carly’s personal and professional travel will be written on the lab whiteboard so all lab members can reference when she is out of town.* If you are comfortable, I encourage you to do the same. This allows your lab-mates to know when you are likely to be unavailable for collaboration or support, and is useful for planning lab activities.

***Undergraduate students*** should discuss vacations with Carly directly.
